apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: usuarios-db:3306
  db_name: msvc_usuarios
  db_username: root
  cursos_url: msvc-cursos:8002
  spring-profiles-active: dev
  msvc-usuarios.yml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de produccion
    ---
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: msvc-cursos
data:
    port: "8002"
    db_host: cursos-db:5432
    db_name: msvc_cursos
    db_username: postgres
    usuarios_url: msvc-usuarios:8001
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type:  Opaque
data:
  username: cm9vdA==
  password: c2FzYQ==
---
apiVersion: v1
kind: Secret
metadata:
    name: msvc-cursos
type:  Opaque
data:
    username: cG9zdGdyZXM=
    password: c2FzYQ==




