apiVersion: apps/v1
kind: Deployment
metadata:
  name: cursos-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cursos-db
  template:
    metadata:
      labels:
        app: cursos-db
    spec:
      containers:
      - image: postgres:15
        name: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: sasa
        - name: POSTGRES_DB
          value: msvc_cursos
        volumeMounts:
        - name: data-postgres
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          hostPath:
            path: /var/lib/postgresql/data
            type: DirectoryOrCreate