apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msvc-usuarios
  name: msvc-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-usuarios
  strategy: {}
  template:
    metadata:
      labels:
        app: msvc-usuarios
    spec:
      containers:
      - image: faccordoba/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: DB_HOST
          value: usuarios-db:3306
        - name: DB_NAME
          value: msvc_usuarios
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: sasa
        resources: {}
        imagePullPolicy: Always
status: {}
