apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msvc-usuarios
  name: msvc-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-usuarios
  strategy: {}
  template:
    metadata:
      labels:
        app: msvc-usuarios
    spec:
      containers:
      - image: faccordoba/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: msvc-usuarios
              key: port
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: msvc-usuarios
              key: db_host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: msvc-usuarios
              key: db_name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: msvc-usuarios
              key: db_username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: msvc-usuarios
              key: password
        - name: CURSOS_URL
          valueFrom:
            configMapKeyRef:
              name: msvc-usuarios
              key: cursos_url
        resources: {}
        imagePullPolicy: Always
status: {}
