apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: usuarios-db
  name: usuarios-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios-db
  template:
    metadata:
      labels:
        app: usuarios-db
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: msvc-usuarios
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: msvc-usuarios
              key: db_name
        volumeMounts:
        - name: data-mysql
          mountPath: /var/lib/mysql
      volumes:
        - name: data-mysql
          persistentVolumeClaim:
            claimName: mysql-pvc