version: "3.9"
services:
  cursos-db:
    container_name: cursos-db
    image: postgres:15
    ports:
      - "5432:5532"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msvc_cursos
    volumes:
      -  data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-cursos:
    container_name: msvc-cursos
    image: faccordoba/usuarios:latest
    env_file:
      - msvc.cursos/.env
#    build:
#      context: ./
#      dockerfile: ./msvc.cursos/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - spring
    depends_on:
      - cursos-db
      - msvc-usuarios
    restart:
        always


volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring
    external: true
    driver: bridge

